# ─────────────────────────────────────────────────────
# 🎲 GLOBAL CONFIGURATION
# ─────────────────────────────────────────────────────

# Project Information
project_name: "motivation"

# LLM Configuration
llm:
  default_model: "meta-llama-3.1-8b-instruct"
  seed: 0  # Will be randomized at runtime if not specified

# Voice Generation Configuration
voice:
  zonos_tts_server: "http://localhost:5001/generate"
  voice_samples:
    - "C:\\ML\\database\\voice\\Linus_LTT.mp3"
    - "C:\\ML\\database\\voice\\DankPods.mp3"
    - "C:\\ML\\database\\voice\\Krizzp.mp3"
    - "C:\\ML\\database\\voice\\Vex.mp3"
  speech_rate: "15"
  normalization:
    target_db: -20.0  # Target dB level for audio normalization
    enabled: true     # Whether to automatically normalize generated voice lines

# Video Generation Configuration
video:
  imagemagick_binary: "C:\\Dev\\ImageMagick\\magick.exe"
  background_music_volume: 0.2  # Volume multiplier for background music (0.0 to 1.0)
  voice_narration_volume: 1.0   # Volume multiplier for voice narration (0.0 to 1.0)
  use_consistent_font: true     # Use the same font for all slides in a scenario

# Emotions List
emotions:
  - "happiness"
  - "sadness"
  - "disgust"
  - "fear"
  - "surprise"
  - "anger"
  - "neutral"

# Directory Configuration
directories:
  # Input directories
  videos_dir: "lib/videos"
  music_dir: "lib/music"
  fonts_dir: "lib/fonts"
  emoji_fonts_dir: "lib/fonts_emoji"
  
  # Output directories (will be created under output/{project_name}/)
  scenarios: "scenarios"
  voice_lines: "voice_lines"
  output_videos: "videos"
